apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-world-pdb
  namespace: demo-dev
  labels:
    app: hello-world
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: hello-world
